name: TheJailBreakShow
version: 1.0
main: com.thejailbreakshow.TheJailBreakShow
api-version: 1.21
commands:
  jb:
    description: JailBreak main command
    usage: /jb debug
  jb_setregion:
    description: Set a region
    usage: /jb setregion <name> <type>
    aliases: [jsetregion]
  setcellbutton:
    usage: /
    description: Set the cell opening button
  gang:
    description: Gang system commands
  gold:
    description: View your current Gold balance